stages:
  - setup
  - unit_test
  - build
  - deploy
  - e2e_test

cache:
  paths:
    - node_modules/

# setup
setup:
  stage: setup
  tags:
    - HostShell

  script:
    - npm install

# unit test
unit_test:
  stage: unit_test

  tags:
    - HostShell

  script:
    - npm run test:unit

# build
build:
  stage: build
  tags:
    - HostShell

  script:
    - npm run build

  artifacts:
    paths:
      - build

# now deployment
deploy:
  stage: deploy

  tags:
    - HostShell

  script:
    - rm ~/.now/auth.json
    - ./node_modules/.bin/now --token=$NOW_TOKEN
    - ./node_modules/.bin/now alias --token=$NOW_TOKEN

  dependencies:
    - build

  only:
    - tags

# e2e tests
e2e_test:
  stage: e2e_test

  tags:
    - HostShell

  script:
    - npm run test:e2e

  dependencies:
    - build
    - deploy

  only:
    - tags
